### ISSUE TITLE
Qüestion?

### ISSUE THREAD

**Issue by certifirm** [BinaryDevil/binance-pump-bot#1]
Where is the amount that I want to use in the pump?

**Comment by BinaryDevil** [comment]
well, it's hardwritten in the code, by default it tries to use 93% of all your available BTC(pump-config.js -> TRADE_IN).

it's not exposed to config yet

**Comment by certifirm** [comment]
Thanks for the answer.  And why 93%?  :-)

**Comment by BinaryDevil** [comment]
Well, 100% will fail as price goes up too fast.

93% is 60% + 11% + 11% + 11%, 4 orders, and it ensures max purchase volume possible

**Comment by certifirm** [comment]
Sorry.  I read in README, but you was faster than me.
