### ISSUE TITLE
QUANTITY IS SMALLER THAN MIN

### ISSUE THREAD

**Issue by ghostrox** [BinaryDevil/binance-pump-bot#19]
I'm trying to test the bot with small amount of money.. only about 8 dollars worth btc, I can place orders in binance no problem but the bot says quantity is smaller than min..

Any solutions?![IMG_20210408_184611475.jpg](https://user-images.githubusercontent.com/62038820/114080248-cfac7880-98c8-11eb-9043-e2f428f4e2fb.jpg)

**Comment by BinaryDevil** [comment]
This is because binance has a minimum quantity for each trading pair, when the amount is not greater than that, it fails.

Check [here](https://binance-docs.github.io/apidocs/spot/en/#filters)

**Comment by ghostrox** [comment]
I guessed so...but I'm confused that that it allows me to buy it on binance without any issues..but the bot was having trouble unfortunately..well so do i need 0.001 btc for transactions?
