### ISSUE TITLE
Question about Config file 

### ISSUE THREAD

**Issue by NetRider-999** [BinaryDevil/binance-pump-bot#2]
First of all, thanks for your work and for sharing the code! 

Could you please write explanations for non-professional traders, for example, what does this mean:

// Should market price BUY ALL upon symbol
config.BUY_UPON_SYMBOL = true
// How many X before take profit happens (will sell 100%)
config.HARD_TAKE_PROFIT = 3.3 -  **_**does this means 100x3.3=330 ?**_**
// Where to stop loss
config.HARD_STOP_LOSS = 0.75

**Comment by BinaryDevil** [comment]
config.HARD_TAKE_PROFIT = 3.3 means the script will automatically sell 100% market price, when your profit is 330%.

it means 3.3x

e.g. when you buy at 0.00000100 XVG/BTC, it will sell all of the balance (via market price order) when price hits 0.00000330 XVG/BTC

the price is updated via websocket/rest api, both are working together

**Comment by BinaryDevil** [comment]
I'll update the code comments later

**Comment by BinaryDevil** [comment]
To clarify, profit is not counted with the real price that your order are made, it's the price at the moment when buy orders are placed.

**Comment by redboxx91** [comment]
what about "use balance" amount/percent setup?
the bot is using all the balance when is making the buy?

**Comment by malikfarooq111** [comment]
can you help me when i command npm start the error comes script is missing please tell me my mistake
